### Тема: Решение систем линейных уравнений

**Выполнил**: Лежнин Максим Витальевич (ПМ-21)

**Преподаватель**: Гурьянов М.А., кафедра ВМ-1

###### Лабораторная работа № **6**, вариант № **23**

###### Весенний семестр, 2023 год

###### МИЭТ, Зеленоград

# Теоретическая справка

#### Методы решения СЛАУ
Пусть требуется найти решение системы:
$$
\begin{cases}
a_{11}x_1 + a_{12}x_2 + ... + a_{1n}x_n = f_1, \\
a_{21}x_1 + a_{22}x_2 + ... + a_{2n}x_n = f_2, \\
... \\
a_{n1}x_1 + a_{n2}x_2 + ... + a_{nn}x_n = f_n
\end{cases}
$$

Или в компактной (векторной) форме: $A \times X = F$.
Мы будем счиать, что $\Delta = \det{A} \neq 0$, то есть решение системы существует и единственно.

Для решения СЛАУ существуют разные методы. Например метод Крамера. Но метод Крамера оказывается неэффективным для больших систем. Рассмотрим более эффективный метод Гаусса.

#### Метод Гаусса
Метод состоит из прямого и обратного хода.

В прямом ходе система уравнений с помощью элементарных преобразований строк матрицы приводится к верхнетреугольному виду. Проще объяснить работу метода на примере системы из 3 уравнений:
$
\left(
\begin{array}{ccc|c}
a_{11} & a_{12} & a_{13} & f_1 \\
a_{21} & a_{22} & a_{23} & f_2 \\
a_{31} & a_{32} & a_{33} & f_3 \\
\end{array}
\right)
\to
\left(
\begin{array}{ccc|c}
a_{11} & a_{12} & a_{13} & f_1 \\
0 & a_{22}^{(1)} & a_{23}^{(1)} & f_2^{(1)} \\
0 & a_{32}^{(1)} & a_{33}^{(1)} & f_3^{(1)} \\
\end{array}
\right)
\to
\left(
\begin{array}{ccc|c}
a_{11} & a_{12} & a_{13} & f_1 \\
0 & a_{22}^{(1)} & a_{23}^{(1)} & f_2^{(1)} \\
0 & 0 & a_{33}^{(2)} & f_3^{(2)} \\
\end{array}
\right)
$

Однако порядок последовательного исключения переменных может может сильно сказаться на результатах расчетов. Уменьшить опасность подобного рода, то есть уменьшить в процессе выкладок вероятность деления на малые числа, позволяют варианты метода Гаусса с выбором главного элемента. 

##### Выбор главного элемента по столбцам.
Перед исключение $x_1$ отсыкивается $\max\limits_i |a_{i1}|$. Допсутим, максимум соответствует $i = i_0$. Тогда первое уравнение в исходной системе меняем местами с уравнением $i_0$. После этого осуществляется первый шаг исключения. Затем перед исключением $x_2$ из оставшихся уравнений отыскивается $\max\limits_{2 \leq i \leq n} |a_{i2}^{(1)}|$, осуществляется соответствующаяперестановка уравнений и так далее.

##### Выбор главного элемента по строке.
Перед исключение $x_1$ отсыкивается $\max\limits_j |a_{1j}|$. Допсутим, максимум соответствует $j = j_0$. Тогда поменяем взаимно номера у неизвестных $x_1$ и $x_{j_0}$ и приступим к процедуре исключения $x_1$ и так далее. 

Впрочем, в прикладных задачах довольно часто фигурируют такие линейные системы, при решении которых можно не менять порядок исключения переменных. Это системы, для матриц которых выполнено условие диагонального преобладания:
$|a_{ii}| > \sum\limits_{j \neq i} |a_{ij}|$ для всех $i = \overline{1,\, n}$.
Это условие остается справедливым даже после каждого шага исключения в процессе приведения матрицы к треугольному виду.

#### Относительная погрешность решения
$$
\frac{\lVert \delta x \rVert}{\lVert x \rVert} \lesssim \mu_A \left( \frac{\lVert \delta f \rVert}{\lVert f \rVert} + \frac{\lVert \delta A \rVert}{\lVert A \rVert} \right),
$$
где $\mu_A = \lVert A^{-1} \rVert \cdot \lVert A \rVert$ - число обусловленности матрицы A.

# Лабораторная работа:

In [32]:
import numpy as np
from random import randint
import matplotlib.pyplot as plt
from sympy import *

### Задание 1
Задайте матрицу A и вектор-столбец f системы линейных уравнений $AX = f$, используя генератор случайных чисел. Очевидно, можно получить решение таким образом: $X = A^{-1}f$ или по правилу Крамера. Реализуйте и проверьте работоспособность этих методов.

In [2]:
# solving system of linear equations with inverse matrix method
def solve_inverse_matrix(A, f):
    if np.linalg.det(A):
        return np.matmul(np.linalg.inv(A), f)
    return []

# Cramer's rule for solving system of linear equations
def solve_cramer(A, f):
    delta = np.linalg.det(A)
    if delta:
        answer = []
        for i in range(len(f)):
            tmp = A.copy()
            tmp[:, i] = f[:, 0]
            answer.append(np.linalg.det(tmp) / delta);
        return np.matrix(answer).T
    return []

In [3]:
# number of variables
N = 5

# random matrix
A = np.random.randint(20, size=(N, N))
f = np.random.randint(20, size=(N, 1))

print("Matrix:")
print(A)
print()
print("Vector of values:")
print(f)
print()

solution_1 = solve_inverse_matrix(A, f)
solution_2 = solve_cramer(A, f)
if (len(solution_1)):
    print("Inverse matrix method solution:")
    for i in range(len(solution_1)):
        print("x_", i, " = ", solution_1[i, 0], sep="")
    print()
    print("Cramer's method solution:")
    for i in range(len(solution_2)):
        print("x_", i, " = ", solution_2[i, 0], sep="")

Matrix:
[[18 19 15 12  0]
 [11 16 17  4 18]
 [ 9  8 15  4  6]
 [ 1 17  4 18  8]
 [19 15  3  6  3]]

Vector of values:
[[ 8]
 [15]
 [ 6]
 [ 4]
 [19]]

Inverse matrix method solution:
x_0 = 1.2560153425027891
x_1 = -0.5562755567571225
x_2 = -0.552963738974688
x_3 = 0.3546179581629554
x_4 = 1.0036751039167313

Cramer's method solution:
x_0 = 1.2560153425027847
x_1 = -0.5562755567571219
x_2 = -0.5529637389746881
x_3 = 0.35461795816295544
x_4 = 1.0036751039167324


### Задание 2
Напишите программу находения решения системы линейных уравнений методом Гаусса с выбором главного элемента.

In [4]:
# Gaussian elimination method for solving system of linear equations
def solve_gauss(A, f, choosing = 0):
    n = len(f)
    for i in range(n):
        # choosing main element by column
        if choosing:
            max_by_col = i
            for j in range(i + 1, n):
                if abs(A[j, i]) > abs(A[max_by_col, i]):
                    max_by_col = j
            if A[j, i] == 0:
                continue
    
            # swapping rows
            f[i, 0], f[max_by_col, 0] = f[max_by_col, 0].copy(), f[i, 0].copy()
            A[max_by_col, :], A[i, :] = A[i, :].copy(), A[max_by_col, :].copy()
        
        # normalization and elemination
        f[i, 0] = f[i, 0] / A[i, i]
        A[i, :] = A[i, :] / A[i, i]
        for j in range(i + 1, n):
            f[j, 0] -= A[j, i] * f[i, 0]
            A[j, :] -= A[j, i] * A[i, :]

    # finding roots
    for i in range(n - 1, -1, -1):
        for j in range(i - 1, -1, -1):
            f[j, 0] -= A[j, i] * f[i, 0]
            A[j, i] = 0
    return f

In [5]:
# number of variables
N = 5

# random matrix
A = np.random.randint(20, size=(N, N)).astype("float")
f = np.random.randint(20, size=(N, 1)).astype("float")

print("Matrix:")
print(A)
print()
print("Vector of values:")
print(f)
print()

solution = solve_gauss(A.copy(), f.copy(), 1)
print("Gaussian elimination method solution:")
for i in range(len(solution)):
    print("x_", i, " = ", solution[i, 0], sep="")
print()

Matrix:
[[15.  2.  6. 10. 17.]
 [13.  6.  7. 16. 17.]
 [ 1.  9. 10. 15.  4.]
 [14. 18. 15.  1. 13.]
 [18. 10.  6. 14.  6.]]

Vector of values:
[[ 8.]
 [19.]
 [ 9.]
 [12.]
 [11.]]

Gaussian elimination method solution:
x_0 = -0.6810470388860901
x_1 = 2.1615810928411126
x_2 = -2.3350616039939545
x_3 = 0.5544405258095543
x_4 = 1.3152063390280768



### Задание 3
Функция rref также приводит матрицу $[A,\, f]$ к диагональному виду, из которого сразу же видно решение системы. Также есть операция левого матричного деления, с помощью которой очень просто найти решение: $X = A \backslash f$.  

In [6]:
# number of variables
N = 5

# random matrix
A = np.random.randint(20, size=(N, N))
f = np.random.randint(20, size=(N, 1))
Af = np.concatenate((A.copy(), f.copy()), axis=1)

print("Extended matrix:")
print(Af)
print()

rref_solution = np.array(Matrix(Af).rref()[0][:, N].evalf())
print("Solution by rref:")
for i in range(len(rref_solution)):
    print("x_", i, " = ", rref_solution[i, 0], sep="")
print()

lstsq_solution = np.linalg.lstsq(A.copy(), f.copy(), rcond=None)[0]
print("Solution by lstsq:")
for i in range(len(lstsq_solution)):
    print("x_", i, " = ", lstsq_solution[i, 0], sep="")
print()

Extended matrix:
[[11  7  3 13 11 13]
 [ 0  2  7 16 17 17]
 [ 2  8 17  1 19 17]
 [ 2 18 12  6 12 12]
 [13 18  0  6 11  8]]

Solution by rref:
x_0 = 0.222982321291314
x_1 = -0.119677171406610
x_2 = 0.499846272098386
x_3 = 0.375710991544965
x_4 = 0.454650269023828

Solution by lstsq:
x_0 = 0.22298232129131346
x_1 = -0.11967717140660933
x_2 = 0.49984627209838495
x_3 = 0.37571099154496557
x_4 = 0.454650269023829



### Задание 4
Задайте случайным образом матрицу A размерности $20 \times 20$ и вектор X. Определите число обусловленности матрицы A с помощью функции cond. Изменяя значения некоторых элементов матрицы A, добейтесь, чтобы ее число обусловленности стало больше $10^3$. Используя A и X, найдите вектор $f = AX$. Полагая вектор X неизвестным, решите систему линейный уравнений всеми предложенными выше методами и сравните найденные результаты с уже известным. Какой из методов дал более точный результат? 

In [53]:
# number of variables
N = 20

while 1:
    A = np.random.randint(20, size=(N, N)).astype("float")
    mu_A = np.linalg.cond(A)
    if mu_A > 10**3:
        break

X = np.random.randint(20, size=(N, 1)).astype("float")
f = np.matmul(A, X)

solution_1 = solve_inverse_matrix(A.copy(), f.copy())
solution_2 = solve_cramer(A.copy(), f.copy())
solution_3 = solve_gauss(A.copy(), f.copy())
solution_4 = solve_gauss(A.copy(), f.copy(), 1)

max_error_1 = 0
print("Inverse matrix method solution:")
for i in range(len(solution_1)):
    #print("x_", i, " = ", solution_1[i, 0], sep="")
    #print("Error for x_", i, " = ", abs(X[i, 0] - solution_1[i, 0]), sep="")
    #print()
    if max_error_1 < abs(X[i, 0] - solution_1[i, 0]):
        max_error_1 = abs(X[i, 0] - solution_1[i, 0])
print("MAX ERROR:", max_error_1)
print("--------------------------------------------")

max_error_2 = 0
print("Cramer's method solution:")
for i in range(len(solution_2)):
    #print("x_", i, " = ", solution_2[i, 0], sep="")
    #print("Error for x_", i, " = ", abs(X[i, 0] - solution_2[i, 0]), sep="")
    #print()
    if max_error_2 < abs(X[i, 0] - solution_2[i, 0]):
        max_error_2 = abs(X[i, 0] - solution_2[i, 0])
print("MAX ERROR:", max_error_2)
print("--------------------------------------------")

max_error_3 = 0
print("Gaussian elimination method solution (without choosing main element):")
for i in range(len(solution_3)):
    #print("x_", i, " = ", solution_3[i, 0], sep="")
    #print("Error for x_", i, " = ", abs(X[i, 0] - solution_3[i, 0]), sep="")
    #print()
    if max_error_3 < abs(X[i, 0] - solution_3[i, 0]):
        max_error_3 = abs(X[i, 0] - solution_3[i, 0])
print("MAX ERROR:", max_error_3)
print("--------------------------------------------")

max_error_4 = 0
print("Gaussian elimination method solution (with choosing main element):")
for i in range(len(solution_4)):
    #print("x_", i, " = ", solution_4[i, 0], sep="")
    #print("Error for x_", i, " = ", abs(X[i, 0] - solution_4[i, 0]), sep="")
    #print()
    if max_error_4 < abs(X[i, 0] - solution_4[i, 0]):
        max_error_4 = abs(X[i, 0] - solution_4[i, 0])
print("MAX ERROR:", max_error_4)
print("--------------------------------------------")

Inverse matrix method solution:
MAX ERROR: 2.2282620193436742e-11
--------------------------------------------
Cramer's method solution:
MAX ERROR: 4.846789636303583e-12
--------------------------------------------
Gaussian elimination method solution (without choosing main element):
MAX ERROR: 1.2163781093477155e-10
--------------------------------------------
Gaussian elimination method solution (with choosing main element):
MAX ERROR: 4.476419235288631e-13
--------------------------------------------


Из всех методов наименьшую погрешность дает метод Гаусса с выбором главного элемента.

### Дополнительное задание
В качестве дополнительного задания напишу универсальную функцию, которая будет решать любую систему уравнений.

In [45]:
def universal_solver(A, f, particular_solution = 0):
    num_of_equations = A.shape[0]
    num_of_variables = A.shape[1]

    C = np.concatenate((A.copy(), f.copy()), axis=1)
    
    rank_A = np.linalg.matrix_rank(A)
    rank_C = np.linalg.matrix_rank(C)
    # checking if system has any solutions
    if rank_A != rank_C:
        print("System is inconsistent!")
        return np.ones((0, 0))
    
    # checking if system is homogeneous
    homogeneous = 1
    for i in range(len(f)):
        if f[i, 0] != 0:
            homogeneous = 0
            break
    
    # when system has only one solution
    if rank_A == num_of_variables:
        if homogeneous:
            print("System is homogeneous and has only one solution - all zeros")
            return f
        print("System is not homogeneous and has only one solution - solving by Gaussian elimination method (with choosing main element)")
        return solve_gauss(A.copy(), f.copy(), 1)
        
    # when system has infinitly many solutions
    print("System has infinitly many solutions")
    number_of_free_variables = num_of_variables - rank_A
    # changing some rows and columns
    X = np.matrix(symbols("x0:%d"%num_of_variables)).T
    D = np.matmul(np.matrix(Matrix(A).rref()[0]), X)
    
    # getting symbolical solution
    i = 0
    j = 0
    while i < rank_A:
        if diff(D[i, 0], X[j, 0]) != 0:
            X[j, 0] = solve(D[i, 0], X[j, 0])[0]
            i += 1
        j += 1
    
    # getting particular solution by assuming all variables are 1
    if particular_solution:
        print("Getting one particular solution by assuming all variables are 1")
        for i in range(X.shape[0]):
            for j in symbols("x0:%d"%num_of_variables):
                X[i, 0] = X[i, 0].subs(j, 1)
    return X
                

In [49]:
# number of equations 
#N = 3
N = randint(2, 6)
# number of variables
#M = 4
M = randint(2, 6)

# random matrix
A = np.random.randint(10, size=(M , N)).astype("float")
f = np.random.randint(10, size=(M, 1)).astype("float")

# test 1
#A = np.matrix([[2, -3, 5, 7], [4, -6, 2, 3], [2, -3, -11, -15]])
#f = np.matrix([[0], [0], [0]])

print("Matrix:")
print(A)
print()
print("Vector of values:")
print(f)
print()

solution = universal_solver(A, f, 1)
for i in range(solution.shape[0]):
    print("Root x_", i, " = ", solution[i, 0], sep="")

Matrix:
[[9. 4. 0. 6. 8. 1.]
 [7. 5. 6. 8. 2. 5.]]

Vector of values:
[[9.]
 [6.]]

System has infinitly many solutions
Getting one particular solution by assuming all variables are 1
Root x_0 = 0.529411764705882
Root x_1 = -4.94117647058824
Root x_2 = 1
Root x_3 = 1
Root x_4 = 1
Root x_5 = 1
